### ISSUE TITLE
Delete that unnecessary comment.

### ISSUE THREAD

**Issue by eliasgruenewald** [phiphi282/Frudo#11]
https://github.com/phiphi282/Frudo/blob/999fa1f292561512bc99cec67073f2677b1f79ba/polls/views.py#L9

**Comment by jreicht** [comment]
Automatically generated comments may be helpful for new users. In addition, it is not a good idea to decide a comment's helpfulness by each single comment because different people may evaluate it differently. Hence, the comments are kept.
