### ISSUE TITLE
missing development account

### ISSUE THREAD

**Issue by Semphora** [phiphi282/Frudo#15]
create a development account with simple (ie. short generic logins)

**Comment by eliasgruenewald** [comment]
`rm db.sqlite3`
`rm -rf dcp/migrations`
`rm -rf dcp/__pycache__`
`python3 manage.py makemigrations dcp`
`python3 manage.py migrate`
`echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@dcp.org', 'disaster2016')" | python3 manage.py shell`
`python3 manage.py runserver`

**Comment by eliasgruenewald** [comment]
Ersetze `dcp` durch `todo`oder `tasks`

**Comment by phiphi282** [comment]
Es gibt jetzt ein Shell Script um eine initiale Datenbank zu erstellen
